### PR TITLE
 testserver updated

### PR DESCRIPTION
**Pull request by masters3d**
https://www.npmjs.com/package/@microsoft.azure/autorest.testserver

### CODE REVIEW

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by masters3d** [comment]
by the way, can you point me to the right direction to find basic usage?

I am trying to generate the files needed for a custom lang extension.

```
AutoRest code generation utility [version: 2.0.4262; node: v9.2.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.1.22->2.1.22)
[Exception] No input files provided.
```

**Comment by olydis** [comment]
@masters3d May I ask what your goal is? Both with this PR (note that the downgrade fails CI since it's missing some newer tests) and with the "basic usage" you're looking for 🙂 Note that this repo, compared to the TypeScript generator you mention, has no standalone meaning, i.e. it does not generate any usable source code. At best, it generates an intermediate representation consumed by the generators (that one you can get by running `--use=@microsoft.azure/autorest.modeler@latest --standalone-modeler --output-artifact=code-model-v1.yaml`). General usage information can be found in our [main repo](https://github.com/Azure/autorest/blob/master/docs/user/cli.md) or by running `autorest --help`. You mention a custom lang extension, may I ask which? We'd be super happy to help, just need more information 😃

**Comment by masters3d** [comment]
>You mention a custom lang extension, may I ask which? We'd be super happy to help, just need more information 😃

My main goal is to contribute to https://github.com/Azure/autorest.swift and other related swift sdk projects. I'd like to get involved in making the skd more "swifty" :)

> May I ask what your goal is? Both with this PR (note that the downgrade fails CI since it's missing some newer tests) and with the "basic usage" you're looking for 🙂 

Well, I was trying to understand how to generate my own API but I could not figure out how to get the swagger files. So I was hoping I could generate them myself. (I pretty much got into a rabbit hole.)  I feel pretty close but I need to figure out how to generate the files needed to actually create the client. This is why I ended up here trying to figure out how to do that . :) I could figure out how to update the tests but that would just Yak shaving for me at this point. 

image

**Comment by olydis** [comment]
@masters3d ahhhh I see, cool to see your interest in that! 

> I could not figure out how to get the swagger files

Well, not sure what you mean with "how to get" it, note that Swagger files serve as the *input* to AutoRest, so they must be authored by someone or created with some tool - at least that's not what AutoRest does. Note sure which Swagger file you're looking out for in particular, but if it's about anything Azure related or you just want *any* Swagger file to play with: [This](https://github.com/Azure/azure-rest-api-specs) repo contains a ton of them 🙂 Well, I assume you know how to then generate something, that's all documented under said link (and `autorest --help` and such) but reach out if you encounter any problems!

For *working* on the Swift extension, follow [this](https://github.com/Azure/autorest/blob/master/docs/developer/autorest-extension.md) guide 🙂

**Comment by masters3d** [comment]
Thanks! So many yaks fo shave for my end goal. haha.

**Pull request closed without merging**
