### PR TITLE
default host

### PR DESCRIPTION
**Pull request by olydis**
fixes https://github.com/Azure/autorest/issues/2746

### CODE REVIEW

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.3.1*

## ❌️ General: 0%

no tests were run for this category


## ❌️ Azure: 0%

no tests were run for this category

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.3.1*

## ❌️ General: 0%

no tests were run for this category


## ❌️ Azure: 0%

no tests were run for this category

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.3.1*

## ❌️ General: 0%

no tests were run for this category


## ❌️ Azure: 0%

no tests were run for this category

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.3.1*

## ❌️ General: 0%

no tests were run for this category


## ❌️ Azure: 0%

no tests were run for this category

**Comment by JasonSmyr** [comment]
This change seems to have caused issue #2978

**Pull request merged**
